from PAYER_TALKER_EVALUATE import PAYER_TALKER_EVALUATE
from TRANSCRIBER_TALKER_EVALUATE import TRANSCRIBER_TALKER_EVALUATE
from EPHEMERAL_TALKER_EVALUATE import EPHEMERAL_TALKER_EVALUATE
from SELFIE_TALKER_EVALUATE import SELFIE_TALKER_EVALUATE
from ISSUER_TALKER_EVALUATE import ISSUER_TALKER_EVALUATE
from TALKER_EVALUATE_BASE import TALKER_EVALUATE_BASE


class TALKER_EVALUATE(
    EPHEMERAL_TALKER_EVALUATE,
    ISSUER_TALKER_EVALUATE,
    PAYER_TALKER_EVALUATE,
    SELFIE_TALKER_EVALUATE, 
    TRANSCRIBER_TALKER_EVALUATE,
    TALKER_EVALUATE_BASE):

    pass